In [2]:
import numpy as np

In [3]:
data = np.random.randn(2,3)

In [4]:
data

array([[ 0.37578835,  0.50997623, -0.43188467],
       [-1.1933843 , -0.90217956,  2.27933117]])

In [5]:
print(data)

[[ 0.37578835  0.50997623 -0.43188467]
 [-1.1933843  -0.90217956  2.27933117]]


In [6]:
data * 33

array([[ 12.40101565,  16.82921544, -14.25219395],
       [-39.38168181, -29.77192564,  75.21792852]])

In [7]:
data + data

array([[ 0.75157671,  1.01995245, -0.86376933],
       [-2.38676859, -1.80435913,  4.55866233]])

In [8]:
data.shape

(2, 3)

In [9]:
print(data.shape)

(2, 3)


In [12]:
data.dtype

dtype('float64')

In [13]:
data1 = [3,4,5,6.6,1]
arr1 = np.array(data1)
arr1

array([3. , 4. , 5. , 6.6, 1. ])

In [18]:
data2 = [[1,2,3,4],[5,6,7,8],[3,3,3,3]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [3, 3, 3, 3]])

In [19]:
arr2.shape

(3, 4)

In [21]:
# 嵌套层数
arr2.ndim

2

In [22]:
arr1.dtype

dtype('float64')

In [23]:
arr2.dtype

dtype('int32')

In [24]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [28]:
np.empty((2,3,2))

array([[[6.61554941e-312, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 5.40247516e-038]],

       [[5.15060436e-062, 3.14310546e-032],
        [1.10571725e-046, 3.43580063e+179],
        [1.27976280e+165, 5.44417699e-062]]])

In [29]:
np.empty((2,3,2),dtype=int)

array([[[-1748479588,  1071123690],
        [-1455604395,  1071665593],
        [-1810213156, -1076124673]],

       [[  570149932, -1074587622],
        [-1379518443, -1074995545],
        [  -90226597,  1073888273]]])

In [30]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
data3 = np.eye(3)
data3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
arr1 = np.array([1,2,3],dtype=np.float)

In [9]:
arr2 = np.array([1,2,3],dtype=int)

In [10]:
arr1.dtype

dtype('float64')

In [11]:
arr2.dtype

dtype('int32')

In [12]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [14]:
float_arr = arr.astype(np.float)
float_arr.dtype

dtype('float64')

In [3]:
arr = np.array([3.3,2.2,1.1,5.5])
arr

array([3.3, 2.2, 1.1, 5.5])

In [12]:
arr.astype(int)

array([3, 2, 1, 5])

In [11]:
arrstr = np.array(['1.1','2.2','3.3'],dtype=np.str)
arrstr

array(['1.1', '2.2', '3.3'], dtype='<U3')

In [13]:
arrstr.astype(float)

array([1.1, 2.2, 3.3])

In [20]:
intarr = np.arange(10)
testarr = np.array([.22,.33,.44,.66],dtype=float)
intarr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
intarr.astype(testarr.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [22]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [23]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [24]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [29]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [30]:
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [32]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [33]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arr[5]

5

In [35]:
arr[5:7]

array([5, 6])

In [36]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [37]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [38]:
arr_slice[1] = 666
arr

array([  0,   1,   2,   3,   4,  12, 666,  12,   8,   9])

In [39]:
arr1 = arr[:]
arr1

array([  0,   1,   2,   3,   4,  12, 666,  12,   8,   9])

In [44]:
arr1[:] = 333
arr

array([333, 333, 333, 333, 333, 333, 333, 333, 333, 333])

In [45]:
test = arr[3:6].copy()
test

array([333, 333, 333])

In [46]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[2]

array([7, 8, 9])

In [48]:
arr2d[1][2]

6

In [50]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [51]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
arr3d[0].shape

(2, 3)

In [56]:
old = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [57]:
arr3d[0] = old
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [58]:
arr3d[1,0]

array([7, 8, 9])

In [62]:
arr3d[1][0][2]

9

In [64]:
arr = np.arange(10)

In [65]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [67]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [70]:
arr2d[:2,:2]

array([[1, 2],
       [4, 5]])

In [71]:
arr2d[2,:2]

array([7, 8])

In [72]:
arr2d[:2,2]

array([3, 6])

In [73]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [74]:
arr2d[:,1] = 0
arr2d

array([[1, 0, 3],
       [4, 0, 6],
       [7, 0, 9]])